/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as assetTokenizationSol from "./Asset-Tokenization.sol";
export type { assetTokenizationSol };
export type { FarmNft } from "./FarmNft";
